#!/usr/bin/env ruby

output = 'www/lib/lodash/lodash.custom.min.js'
methods = %w(
  all
  chain
  compact
  contains
  each
  extend
  find
  first
  flatten
  groupBy
  initial
  isEmpty
  isEqual
  isString
  isObject
  isArray
  last
  map
  max
  memoize
  object
  partial
  pick
  pluck
  reduce
  reject
  select
  sortBy
  tap
  throttle
  unique
  value
  values
)

# there is an undefined variable called freeGlobal which breaks "use strict", hence the iife
`lodash modern include=#{ methods.join(',') } --production --output #{ output } iife='!function(window,freeGlobal,undefined){%output%}(this)'`
