defaults: &defaults
  foursquare:
    api_key: 'TQWJCSXTG2SDUZKA1VG1XFPMU3WUKSV2KDDJN1F2HUR3RWLX'
    api_secret: 'HZLOF3O1NGZGLYWSMFL0JD1KG1BZ0DBVKLLF1LJSJOQQMW1T'
  untappd:
    api_key: '5179A350566DBEBC36D2461A4DE650C706FAA492'
    api_secret: '9C875C75150B2D56980637540903600163997657'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  foursquare:
    api_key: <%= ENV['FOURSQUARE_APP_ID'] %>
    api_secret: <%= ENV['FOURSQUARE_APP_SECRET'] %>
  untappd:
    api_key: <%= ENV['UNTAPPD_APP_ID'] %>
    api_secret: <%= ENV['UNTAPPD_APP_SECRET'] %>
